/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlazaRouteImport } from './routes/plaza'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as AuctionsIndexRouteImport } from './routes/auctions.index'
import { Route as AuctionIndexRouteImport } from './routes/auction.index'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as MessagesIdRouteImport } from './routes/messages.$id'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as AuctionsSlugRouteImport } from './routes/auctions.$slug'
import { Route as AuctionIdRouteImport } from './routes/auction.$id'
import { Route as AuctionsNewListingIdRouteImport } from './routes/auctions.new.$listingId'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlazaRoute = PlazaRouteImport.update({
  id: '/plaza',
  path: '/plaza',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIndexRoute = AuctionsIndexRouteImport.update({
  id: '/auctions/',
  path: '/auctions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionIndexRoute = AuctionIndexRouteImport.update({
  id: '/auction/',
  path: '/auction/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProfileRoute,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsSlugRoute = AuctionsSlugRouteImport.update({
  id: '/auctions/$slug',
  path: '/auctions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionIdRoute = AuctionIdRouteImport.update({
  id: '/auction/$id',
  path: '/auction/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsNewListingIdRoute = AuctionsNewListingIdRouteImport.update({
  id: '/auctions/new/$listingId',
  path: '/auctions/new/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/favorites': typeof FavoritesRoute
  '/legal': typeof LegalRoute
  '/listings': typeof ListingsRoute
  '/plaza': typeof PlazaRoute
  '/profile': typeof ProfileRouteWithChildren
  '/sell': typeof SellRoute
  '/wallet': typeof WalletRoute
  '/auction/$id': typeof AuctionIdRoute
  '/auctions/$slug': typeof AuctionsSlugRoute
  '/listing/$id': typeof ListingIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/auction/': typeof AuctionIndexRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/auctions/new/$listingId': typeof AuctionsNewListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/favorites': typeof FavoritesRoute
  '/legal': typeof LegalRoute
  '/listings': typeof ListingsRoute
  '/plaza': typeof PlazaRoute
  '/profile': typeof ProfileRouteWithChildren
  '/sell': typeof SellRoute
  '/wallet': typeof WalletRoute
  '/auction/$id': typeof AuctionIdRoute
  '/auctions/$slug': typeof AuctionsSlugRoute
  '/listing/$id': typeof ListingIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/auction': typeof AuctionIndexRoute
  '/auctions': typeof AuctionsIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/auctions/new/$listingId': typeof AuctionsNewListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/favorites': typeof FavoritesRoute
  '/legal': typeof LegalRoute
  '/listings': typeof ListingsRoute
  '/plaza': typeof PlazaRoute
  '/profile': typeof ProfileRouteWithChildren
  '/sell': typeof SellRoute
  '/wallet': typeof WalletRoute
  '/auction/$id': typeof AuctionIdRoute
  '/auctions/$slug': typeof AuctionsSlugRoute
  '/listing/$id': typeof ListingIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/auction/': typeof AuctionIndexRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/auctions/new/$listingId': typeof AuctionsNewListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/chat'
    | '/contact'
    | '/create'
    | '/favorites'
    | '/legal'
    | '/listings'
    | '/plaza'
    | '/profile'
    | '/sell'
    | '/wallet'
    | '/auction/$id'
    | '/auctions/$slug'
    | '/listing/$id'
    | '/messages/$id'
    | '/profile/$id'
    | '/auction/'
    | '/auctions/'
    | '/messages/'
    | '/auctions/new/$listingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/chat'
    | '/contact'
    | '/create'
    | '/favorites'
    | '/legal'
    | '/listings'
    | '/plaza'
    | '/profile'
    | '/sell'
    | '/wallet'
    | '/auction/$id'
    | '/auctions/$slug'
    | '/listing/$id'
    | '/messages/$id'
    | '/profile/$id'
    | '/auction'
    | '/auctions'
    | '/messages'
    | '/auctions/new/$listingId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/chat'
    | '/contact'
    | '/create'
    | '/favorites'
    | '/legal'
    | '/listings'
    | '/plaza'
    | '/profile'
    | '/sell'
    | '/wallet'
    | '/auction/$id'
    | '/auctions/$slug'
    | '/listing/$id'
    | '/messages/$id'
    | '/profile/$id'
    | '/auction/'
    | '/auctions/'
    | '/messages/'
    | '/auctions/new/$listingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  ChatRoute: typeof ChatRoute
  ContactRoute: typeof ContactRoute
  CreateRoute: typeof CreateRoute
  FavoritesRoute: typeof FavoritesRoute
  LegalRoute: typeof LegalRoute
  ListingsRoute: typeof ListingsRoute
  PlazaRoute: typeof PlazaRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  SellRoute: typeof SellRoute
  WalletRoute: typeof WalletRoute
  AuctionIdRoute: typeof AuctionIdRoute
  AuctionsSlugRoute: typeof AuctionsSlugRoute
  ListingIdRoute: typeof ListingIdRoute
  MessagesIdRoute: typeof MessagesIdRoute
  AuctionIndexRoute: typeof AuctionIndexRoute
  AuctionsIndexRoute: typeof AuctionsIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  AuctionsNewListingIdRoute: typeof AuctionsNewListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plaza': {
      id: '/plaza'
      path: '/plaza'
      fullPath: '/plaza'
      preLoaderRoute: typeof PlazaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/': {
      id: '/auctions/'
      path: '/auctions'
      fullPath: '/auctions/'
      preLoaderRoute: typeof AuctionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/': {
      id: '/auction/'
      path: '/auction'
      fullPath: '/auction/'
      preLoaderRoute: typeof AuctionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$slug': {
      id: '/auctions/$slug'
      path: '/auctions/$slug'
      fullPath: '/auctions/$slug'
      preLoaderRoute: typeof AuctionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/$id': {
      id: '/auction/$id'
      path: '/auction/$id'
      fullPath: '/auction/$id'
      preLoaderRoute: typeof AuctionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/new/$listingId': {
      id: '/auctions/new/$listingId'
      path: '/auctions/new/$listingId'
      fullPath: '/auctions/new/$listingId'
      preLoaderRoute: typeof AuctionsNewListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteChildren {
  ProfileIdRoute: typeof ProfileIdRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileIdRoute: ProfileIdRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  ChatRoute: ChatRoute,
  ContactRoute: ContactRoute,
  CreateRoute: CreateRoute,
  FavoritesRoute: FavoritesRoute,
  LegalRoute: LegalRoute,
  ListingsRoute: ListingsRoute,
  PlazaRoute: PlazaRoute,
  ProfileRoute: ProfileRouteWithChildren,
  SellRoute: SellRoute,
  WalletRoute: WalletRoute,
  AuctionIdRoute: AuctionIdRoute,
  AuctionsSlugRoute: AuctionsSlugRoute,
  ListingIdRoute: ListingIdRoute,
  MessagesIdRoute: MessagesIdRoute,
  AuctionIndexRoute: AuctionIndexRoute,
  AuctionsIndexRoute: AuctionsIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  AuctionsNewListingIdRoute: AuctionsNewListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
